test:
  stage: test
  image: node:15-buster
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  script:
    - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.1/install.sh | bash
    - ". ~/.nvm/nvm.sh"
    - nvm --version
    - nvm install --lts
    - npm install --global yarn
    - yarn
    - yarn test
  cache:
    - paths:
        - coverage/
  artifacts:
    paths:
      - coverage/
    when: always
    reports:
      junit:
        - junit.xml
      cobertura: coverage/cobertura-coverage.xml
